postgres:
  image: postgres:15-alpine
  container_name: {{PROJECT_NAME_SNAKE}}_postgres
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: rootpassword
    POSTGRES_DB: {{PROJECT_NAME_SNAKE}}_db
  ports:
    - '5432:5432'
  volumes:
    - postgres_data:/var/lib/postgresql/data
  restart: unless-stopped
